[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.9.1"
lazy_static = "1.5.0"
rand = "0.9.1"
sdl2 = "0.37.0"

# Configuration spécifique pour macOS
[target.'cfg(target_os = "macos")'.dependencies.sdl2]
version = "0.37.0"
features = ["bundled"]
